### ISSUE TITLE
bug: progress reporters do not get updated

### ISSUE THREAD

**Issue by hq9000** [sunvalley-technologies/php-task-manager#8]
A sync task is doing something like this:

![image](https://user-images.githubusercontent.com/21345604/87430663-34fb6380-c5ee-11ea-8cc4-f6170b8afa5c.png)

another process, at the same time, does the following:
```
            $chunkPromise = $this->getClient()->findTasksByStatus(false, $offset, $limit);
            $chunk        = await($chunkPromise, $this->getLoop());
```

I was expecting that i would be getting a task reporter with "PROCESSING" status and changing completeness, instead, i always get the one in WAITING state (before submission there was no reporters found, so it's apparently the one related to the task). I also doublechecked that the task was actually run (it was).

Similarly, the same problem is observed with async task. 
When tracing down execution of async task, i see event emission and invoking `task-report` RPC (presumably meant to reach the manager process). However, it doesn't seem to invoke a handler in manager (or i failed to catch it somehow).

Also, it seems that calling finishTask did not get progress reporter updated too (not totally sure)

**Summary:**
the problem should be fixed so that both sync and async tasks can report intermediate progress visible to others through findByStatus while the task is being executed.

**Comment by bmlkc** [comment]
First of all there are several problems above:

1. The task that contains a `sleep` is not async.
2. The completion target is 10 while completion goes up to 100. not effecting anything but not logical neither
3. See \SunValley\TaskManager\Tests\Fixtures\Task\TestUpdatingTask and \SunValley\TaskManager\Tests\TaskManagerTest::testTaskManagerRedisStorage , my results are quiet different than yours:

![image](https://user-images.githubusercontent.com/18337504/88072434-4f48ba80-cb75-11ea-9932-9af96e056037.png)

I will check the case with real sync tasks but this issue is not valid for async tasks. You just need to write async tasks.

**Comment by bmlkc** [comment]
I can confirm the issue is present for sync tasks. will patch it. remember that it will only work for tasks that are not LoopAware. hence avoid writing tasks sync tasks derived from AbstractAsyncTask or implementing LoopAware. PTM understands all tasks that are LoopAware as async tasks and not LoopAware as sync tasks.

**Comment by bmlkc** [comment]
on another look, updating progress is not possible for sync tasks as IPC uses loop to start the task and hence the code is run inside the loop already, so the code has to return to send the progress report back with loop which is not possible. if you want progress reporting, you need to write async tasks.
